<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Best_tactile-searchbox-input</name>
   <tag></tag>
   <elementGuidId>23ecf101-dedd-46cd-bc30-3f325179383e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.tactile-searchbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sb_ifc50']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a7a1a6d-fab6-4483-b8f3-399a2fb70d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b7cfef0c-8382-4901-a5bb-f55ed321af62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tactile-searchbox-input</value>
      <webElementGuid>bcc32c75-dda7-4e81-9e81-aac6b68df0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>74301815-0ba1-43c2-911e-d932b8a047d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sbsg50</value>
      <webElementGuid>c1eb9f03-e2fa-4437-bd3d-ce11dfeab9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>2cf9d3f8-19bd-4ef0-9d17-a9a223658598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e882dbe-120c-4a9c-be5f-39e171bc8d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Choose starting point, or click on the map...</value>
      <webElementGuid>73367a2f-822b-4755-b3cb-96ac3f70a0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Choose starting point, or click on the map...</value>
      <webElementGuid>901f1f10-f63b-490b-8bb0-7ed061d493d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Choose starting point, or click on the map...</value>
      <webElementGuid>f20106a0-293c-4793-b1fc-b3a4cf5c6c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sb_ifc50&quot;)/input[@class=&quot;tactile-searchbox-input&quot;]</value>
      <webElementGuid>3f8705cb-d2cf-4262-b896-6a5b2d5d145a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sb_ifc50']/input</value>
      <webElementGuid>df7fee9b-8b2f-48dd-ace7-afae9a1f6b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9b94610d-9f26-465a-8ac1-c8906efe613c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Choose starting point, or click on the map...']</value>
      <webElementGuid>d185de22-9433-42cc-adbd-a92cc225a1c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
