<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drag to change, click to remove_tacti_01712b</name>
   <tag></tag>
   <elementGuidId>c05f161b-032d-44a0-a285-d9cca6c0ed36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.tactile-searchbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sb_ifc50']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>298141a8-6346-49ca-917e-5c1f746d75f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02dbb3c0-66e2-4128-acaa-3e5b2c4aa19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tactile-searchbox-input</value>
      <webElementGuid>65152874-4804-4b77-8420-6e469fdcacec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>bf6d0ca2-468c-4359-8fa2-7542fef0bb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sbsg50</value>
      <webElementGuid>e58d12f2-44c2-46c6-8180-fb34ad0b7bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>b67c7f69-088a-431d-a095-ad15222ef3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>236ff6d6-61b8-4d32-a5e3-af3b96eebf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Starting point Springboro, Ohio</value>
      <webElementGuid>dc092a1c-649e-4f87-8285-176db1e419b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sb_ifc50&quot;)/input[@class=&quot;tactile-searchbox-input&quot;]</value>
      <webElementGuid>e80a3411-0073-4227-a163-80bc23a18aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sb_ifc50']/input</value>
      <webElementGuid>49de269e-5b42-4e80-bed4-60b059130c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f8000d44-2c60-4141-ab7d-6883bb378f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
