<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>5627cb57-e26f-4167-be3f-b1ef8601c75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.StyledButton-iqvzmi-13.SubmitButton-sc-181jrh-14.bqPNZC.GrlVf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cb1b640-b7ca-4226-85c7-e932544f9e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledButton-iqvzmi-13 SubmitButton-sc-181jrh-14 bqPNZC GrlVf</value>
      <webElementGuid>267d10fc-eaec-4d89-bb4e-ba235143e228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>22b2d692-4f5f-43f0-87d6-74e2c4dbabd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-sc-181jrh-12 csHBBP&quot;]/div[@class=&quot;MemberCard-sc-181jrh-11 fTvlCc&quot;]/button[@class=&quot;StyledButton-iqvzmi-13 SubmitButton-sc-181jrh-14 bqPNZC GrlVf&quot;]</value>
      <webElementGuid>0cc2c9a8-1679-4119-9552-ec623e5eb602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/button</value>
      <webElementGuid>c46ed151-0e72-4169-8922-5bb1001c5d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I Need to Activate My Coverage'])[1]/following::button[1]</value>
      <webElementGuid>64e449dd-72d2-4a23-b356-2fee4031344b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Healthfirst Member'])[1]/following::button[1]</value>
      <webElementGuid>78c82cd6-904c-45ad-8417-c97f1b9173f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::button[1]</value>
      <webElementGuid>4f2ee44d-d283-431a-babe-ec2ca98a8f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>c8a3bc3c-45bf-4615-a7db-feae098bb43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fd800fb7-6e1c-4a00-8d41-5d2191f12e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>9de91ee1-471a-4d13-ad5d-a99d582d7bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
