<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Active Healthfirst Member_RadioImg-sc-1_77a051</name>
   <tag></tag>
   <elementGuidId>9343cc4d-801e-4786-b7f2-d49488f6cec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.RadioButtonContainer-sc-181jrh-10.dTVibc > img.RadioImg-sc-181jrh-13.jEILLI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[5]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbbd857c-097d-43a3-819e-b7829ebbf74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/react/images/icn-radio-inactive.svg</value>
      <webElementGuid>adfcdce2-6f0c-414f-aeb2-5eaea1d039f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RadioImg-sc-181jrh-13 jEILLI</value>
      <webElementGuid>d16249cb-fe8f-41e5-a8c7-10e1690003e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-sc-181jrh-12 csHBBP&quot;]/div[@class=&quot;MemberCard-sc-181jrh-11 fTvlCc&quot;]/div[@class=&quot;RadioButtonContainer-sc-181jrh-10 dTVibc&quot;]/img[@class=&quot;RadioImg-sc-181jrh-13 jEILLI&quot;]</value>
      <webElementGuid>16b4bdf5-7719-4929-8f64-973149bf6c74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[5]/img</value>
      <webElementGuid>47ffe724-4b81-4b70-98d7-353bce10833b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/img</value>
      <webElementGuid>040beed5-80c4-470d-90cf-66dddd550e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/react/images/icn-radio-inactive.svg']</value>
      <webElementGuid>b4ab4de7-3387-4667-a63b-da6f04d7c9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
