<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_email</name>
   <tag></tag>
   <elementGuidId>d57a65cd-392a-49b0-8a91-bb4744cdde24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f915fd68-8dd2-43b8-8acb-62f129a0440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95aa45cd-537f-41d6-aec3-863869ff9ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>445448a3-0c3e-49f8-bf76-8b4bbb94593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>you@domain.com</value>
      <webElementGuid>43228443-1556-4618-abe2-5ffad3a0918b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-iqvzmi-6 jEgqwD</value>
      <webElementGuid>09968100-9220-49a7-9a6a-063dc9059d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-sc-181jrh-12 csHBBP&quot;]/div[@class=&quot;MemberCard-sc-181jrh-11 fTvlCc&quot;]/div[@class=&quot;FormGrid-iqvzmi-0 exQBYL&quot;]/div[@class=&quot;InputWrapper-iqvzmi-1 cPvRBR&quot;]/input[@class=&quot;Input-iqvzmi-6 jEgqwD&quot;]</value>
      <webElementGuid>dbc2dc82-0bc2-4823-83fb-4582c8a12ab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>65132ed8-a89a-4d05-9c0b-a26c78f24af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[2]/div[6]/input</value>
      <webElementGuid>e1ac43ab-73e1-4917-8cf7-4969debee18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>0d6394e3-7ed9-484f-8ebc-89037e107882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @placeholder = 'you@domain.com']</value>
      <webElementGuid>2a3f55d8-4895-4197-984e-d6ada63fe09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
