<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_dob</name>
   <tag></tag>
   <elementGuidId>7d665f88-1a25-49ac-b554-5c1c0b1e5f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dob&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c641cfe4-9635-4613-8d8e-c8879c420356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31525642-98c4-40eb-aed8-c21d45c4b90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>d38a1390-c487-4e42-b33e-f00fcefc5d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>f3edf2b9-0957-41d2-9607-f6d369a983a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD</value>
      <webElementGuid>18adf921-ccea-4f27-897f-1cd28636bf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-iqvzmi-6 jEgqwD</value>
      <webElementGuid>df7bbab0-cdb3-4dce-ab0d-3d05f3e74d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-sc-181jrh-12 csHBBP&quot;]/div[@class=&quot;MemberCard-sc-181jrh-11 fTvlCc&quot;]/div[@class=&quot;FormGrid-iqvzmi-0 exQBYL&quot;]/div[@class=&quot;InputWrapper-iqvzmi-1 cPvRBR&quot;]/input[@class=&quot;Input-iqvzmi-6 jEgqwD&quot;]</value>
      <webElementGuid>c3e63698-d567-435f-b5db-56ba6f9e061a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dob']</value>
      <webElementGuid>2e6b5ab6-6e51-4d1a-8b44-fbde72d84be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>9311b308-a9ab-4fdb-90eb-794a4b9a46c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4ec9c070-2ce3-4be7-a03a-f4a889f8b3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dob' and @placeholder = 'MM/DD']</value>
      <webElementGuid>c7b54c98-d347-4f53-8671-4f3e67bd2257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
