<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Email Address_selectCheckbox</name>
   <tag></tag>
   <elementGuidId>24252bfd-6a5d-431d-aba9-b7ef68f738b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectCheckbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectCheckbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07eb4103-3aca-4171-b52b-ddfdc84b6b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ecf26308-3b3b-41d1-8634-818e3f7d0ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectCheckbox</value>
      <webElementGuid>0e83e500-6976-429b-94ae-84d10336f96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectCheckbox</value>
      <webElementGuid>aa90a602-76af-45c2-aae3-cde3a62ebef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CheckBox-iqvzmi-17 dLJzJk</value>
      <webElementGuid>d7eafb0b-68f4-4918-8813-9433ec212e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ab6039c-f60f-4241-80bc-60e01f70f8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectCheckbox&quot;)</value>
      <webElementGuid>ca1b23e0-9612-458e-8a73-cd916a079b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectCheckbox']</value>
      <webElementGuid>7c38b862-8f50-4551-99fd-45dab6e3fa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[2]/div[8]/input</value>
      <webElementGuid>f532ba3d-200f-41a5-a960-77b392247449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>45f6497b-8d9c-4f03-a97b-abefa0a37247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'selectCheckbox' and @id = 'selectCheckbox']</value>
      <webElementGuid>c0276e4f-c3b5-4d8f-8f0e-6b3ce68e0f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
