<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone Number_mobile</name>
   <tag></tag>
   <elementGuidId>0c1b839a-b6aa-4486-8771-8ba5fcc71475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>375dfb7c-1f81-4979-9ea1-309ae971567b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ad8de44-475c-4085-a29e-7f6bb4498fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>0483c962-2d9a-4ffb-9e99-680b0ff5fc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>4ac936ea-fa73-496c-ba46-dfcf7a5ad53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>77fce394-b0d7-4267-a3f7-1a4e83724a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000-000-0000</value>
      <webElementGuid>4f12d021-aca8-40ab-ad25-f11d657a42b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-iqvzmi-6 jEgqwD</value>
      <webElementGuid>d725f720-d3c8-4603-9c2f-05f17f98001a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile&quot;)</value>
      <webElementGuid>4ace4208-6c34-4367-a5ad-c406a28546b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile']</value>
      <webElementGuid>22152601-1d4b-4fec-b8eb-ae98d9971760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[2]/div[5]/input</value>
      <webElementGuid>323344ad-c8fd-4511-948f-96d76c4ef655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6d9aaaeb-8a64-446c-8df0-38ff07325e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mobile' and @id = 'mobile' and @placeholder = '000-000-0000']</value>
      <webElementGuid>5fd5fcd7-dea2-482b-b3d9-cb84b59fe610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
