<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserName_firstName</name>
   <tag></tag>
   <elementGuidId>6ce75d1b-78f1-49c4-845d-35bfa1517d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea30800e-ae25-434c-b362-683e278e0d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d7befa4-e0bf-44bd-abb7-050ec5301a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>9e7cf6e1-8205-4bc0-ab81-5872f4511388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>77da6ca0-b5f6-4d6a-8d0e-fc964c3b3c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a UserName</value>
      <webElementGuid>25ac88ae-75ff-4bd5-8e3f-87408c30ba18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-iqvzmi-6 CustomInput-r52l9b-1 jEgqwD jFKfTr</value>
      <webElementGuid>cccb1f17-63e3-46d5-a40d-6209cb15ba89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-iqvzmi-10 CustomMemberCardContainer-wbbk72-1 drDnnE jAYFF&quot;]/div[@class=&quot;MemberCardsContainer-r52l9b-6 dGoOcp&quot;]/div[@class=&quot;MemberCard-r52l9b-2 ilpCN&quot;]/div[@class=&quot;FormGrid-iqvzmi-0 exQBYL&quot;]/div[@class=&quot;InputWrapper-iqvzmi-1 cPvRBR&quot;]/div[@class=&quot;MemberIdInput-iqvzmi-5 UJRyT&quot;]/input[@class=&quot;Input-iqvzmi-6 CustomInput-r52l9b-1 jEgqwD jFKfTr&quot;]</value>
      <webElementGuid>ba6fb4b7-b95b-458a-bf82-7cc6d6c4d146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
      <webElementGuid>21bd6a36-219e-4201-ac09-862da282cbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>04320b87-11c7-4713-a534-b5a1892823bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>23cd8e09-1313-4627-98b8-60d5b916b689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstName' and @placeholder = 'Enter a UserName']</value>
      <webElementGuid>ab746ac3-d51d-4150-805f-8c995ccbca6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
