<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ni0yopmail.com_Input-iqvzmi-6 jEgqwD</name>
   <tag></tag>
   <elementGuidId>4f1118e5-dd52-4ced-ad1d-afbcb6a03789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Input-iqvzmi-6.jEgqwD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07e4e31d-d74e-4e43-9098-db24088537d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7b5108b5-af5c-48a4-8b8f-7eb7f025dd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d4dd4bd6-2aab-4e64-98d9-a424b034088a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Code</value>
      <webElementGuid>2fd89ecc-471f-44c6-a0f7-4cd2bb18c264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-iqvzmi-6 jEgqwD</value>
      <webElementGuid>6050b2da-84eb-43ef-b256-e0ba3012515e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReactAppWrapper-wide&quot;)/div[@class=&quot;Wrapper-sc-1rarzen-0 jpXMAK&quot;]/div[@class=&quot;Container-sc-1rarzen-2 dKSEYs&quot;]/div[@class=&quot;MemberCardsContainer-iqvzmi-10 CustomMemberCardContainer-wbbk72-1 drDnnE jAYFF&quot;]/div[@class=&quot;MemberCard-iqvzmi-9 bYnpww&quot;]/div[@class=&quot;FormGrid-iqvzmi-0 CustomFormGrid-sc-1cvjk1s-7 exQBYL grhEvF&quot;]/div[@class=&quot;InputWrapper-iqvzmi-1 cPvRBR&quot;]/input[@class=&quot;Input-iqvzmi-6 jEgqwD&quot;]</value>
      <webElementGuid>424b3c1d-d184-491d-98f6-fd935e1d2a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>557c2629-f9fc-486e-a8bb-b289dbad1a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReactAppWrapper-wide']/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>7a868635-6054-4d89-9e63-5e777b12e1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d31537e-55d8-4787-a3ba-ac02fd1e84fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Enter Code']</value>
      <webElementGuid>0ea04cd9-0d47-46a2-9f1a-d1a0dba5e254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
