<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send</name>
   <tag></tag>
   <elementGuidId>4f390ba1-0840-4367-99f0-75687019c35e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ModalSubmitBtn-sc-1quz15x-8.jSkKms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d8538d7-f0e2-425f-892f-873decff694a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>638c11b8-d6c2-46b8-bda2-bdaf7fa848ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ModalSubmitBtn-sc-1quz15x-8 jSkKms</value>
      <webElementGuid>b9e7180a-f912-4cb1-a6cd-669cfe5dac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>0b7d139b-ceb5-4d72-967d-d64b1a622952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-page-provider-search page-template-page-provider-search-php page page-id-65108&quot;]/div[7]/div[@class=&quot;ModalWindow-sc-1quz15x-0 gLkSeA&quot;]/div[@class=&quot;ModalFooter-sc-1quz15x-6 UHsgn&quot;]/button[@class=&quot;ModalSubmitBtn-sc-1quz15x-8 jSkKms&quot;]</value>
      <webElementGuid>90a4135d-1078-4eee-b80e-1fe36d14adc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[5]</value>
      <webElementGuid>834e7b6f-2fc1-4457-82d8-406032422bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>cdcf286a-fe2a-4820-8f32-970495817c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::button[2]</value>
      <webElementGuid>6e33ed4a-d273-4c70-9ea3-7a83d06b8fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>5b18b453-5788-4bcd-b8bf-3ae2d0f7dcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>20fb4bf2-c687-4d26-b994-b80ab7a55cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>5b64d58b-b5b7-4ea2-ba52-00953df4386f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
