<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Healthfirst 65 Plus Plan (HMO)</name>
   <tag></tag>
   <elementGuidId>8187ec45-7544-442c-8fc0-d41a4921ef96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.DropdownFieldText-m03vzn-2.iDLPzL.selected.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdown-field']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1ff0027-5fdf-47e8-8604-a8d09d995a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DropdownFieldText-m03vzn-2 iDLPzL selected false</value>
      <webElementGuid>e31c2020-86be-4516-b170-6ef555ef2af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>378a8061-77ea-490f-bad7-3028370832ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dropdown_text</value>
      <webElementGuid>85f6b7a7-1937-4595-abc0-276f819de8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Healthfirst 65 Plus Plan (HMO)</value>
      <webElementGuid>ca5459cc-5e9b-477d-a536-f95c21f3552b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-field&quot;)/div[@class=&quot;DropdownFieldTextContainer-m03vzn-3 ciDLbR&quot;]/div[@class=&quot;DropdownFieldText-m03vzn-2 iDLPzL selected false&quot;]</value>
      <webElementGuid>47033cd1-7b1c-4dfa-bf60-746bd7cc6562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-field']/div/div</value>
      <webElementGuid>99e2f633-93d4-417e-b391-510b8e74670b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Doctor'])[5]/following::div[23]</value>
      <webElementGuid>0f0f58e8-e588-4cc2-8b7b-c5ec60c600a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中文'])[2]/following::div[29]</value>
      <webElementGuid>62d0d25a-9a7a-46d2-81a5-38c189b08f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Healthfirst 65 Plus Plan (HMO)'])[2]/preceding::div[2]</value>
      <webElementGuid>bb29b119-178e-4a46-9774-d6ee64cb1c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Healthfirst Child Health Plus'])[1]/preceding::div[3]</value>
      <webElementGuid>505d35c2-33ff-4ac6-8509-1cf2e738b7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Healthfirst 65 Plus Plan (HMO)']/parent::*</value>
      <webElementGuid>dacdc5e9-c1ad-4836-8725-bf660b0e5c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>81b0baef-dde4-4bda-a00c-1b7fcac85134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Healthfirst 65 Plus Plan (HMO)' or . = 'Healthfirst 65 Plus Plan (HMO)')]</value>
      <webElementGuid>15985786-cc07-4935-86ae-a13c40cbc62f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
