<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Provider details have been sent success_931390</name>
   <tag></tag>
   <elementGuidId>1099ef4a-d7d0-4a67-82ea-af5d59a56062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.CloseIcon-sc-15vbdd6-6.fGeyER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='toast_msg_close_icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c57f4ce3-8116-4dab-8dfa-4849c4163be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hf-cde-provider-directory.healthfirst.org/embed/assets/images/icn-close-white.png</value>
      <webElementGuid>6262034b-142a-4d36-9c58-4382aebe6f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>toast_msg_close_icon</value>
      <webElementGuid>27ccd4bd-f5a8-4443-a432-e224b2b67db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CloseIcon-sc-15vbdd6-6 fGeyER</value>
      <webElementGuid>99a13742-1ef7-48d5-81b6-813bda2287fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-page-provider-search page-template-page-provider-search-php page page-id-65108&quot;]/div[@class=&quot;react-toast-notifications__container css-px0rfk&quot;]/div[@class=&quot;ToastWrapper-sc-15vbdd6-0 jWkLwW entered&quot;]/div[@class=&quot;ToastContainer-sc-15vbdd6-1 QqkWJ&quot;]/div[@class=&quot;ToastCloseImageContainer-sc-15vbdd6-4 fWUuyx&quot;]/img[@class=&quot;CloseIcon-sc-15vbdd6-6 fGeyER&quot;]</value>
      <webElementGuid>578c4fa3-50a5-4092-9bfc-d14af3f79380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='toast_msg_close_icon']</value>
      <webElementGuid>3e146c62-1390-42f1-bae4-89f538079abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/img</value>
      <webElementGuid>6f9b0a1e-fe12-42a1-ac13-550b3a0f6d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hf-cde-provider-directory.healthfirst.org/embed/assets/images/icn-close-white.png' and @alt = 'toast_msg_close_icon']</value>
      <webElementGuid>92f77c40-6b71-4c0a-b79f-1937d4a3d6b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
