<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_GARY B PALATUCCI, MD</name>
   <tag></tag>
   <elementGuidId>e5fa44ec-bc3d-4cde-a51d-6130ce3dfefe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//p[@type='submit'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>20c5bf95-2a5d-4306-a94f-ba712f305456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cc50cd1d-9db6-439e-ad92-21183de7f385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>323ccfb3-c61e-4da9-afb7-811171048b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ProviderName</value>
      <webElementGuid>bce0f146-e9a7-4963-b745-51ef95f7a00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProviderName-sc-1izdixb-8 bFmWmv</value>
      <webElementGuid>f82b88cf-bad3-4785-984d-a1714c7a3cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GARY B PALATUCCI, MD</value>
      <webElementGuid>b045b14c-4c91-43d3-9add-f764eb3bafbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-dir-outer-container&quot;)/div[@class=&quot;OuterContainer-sc-16fmc9y-1 AGOzA&quot;]/div[@class=&quot;Container-sc-16fmc9y-2 fxuCEC&quot;]/div[@class=&quot;LeftPanel-sc-16fmc9y-3 cLnDLW&quot;]/div[@class=&quot;ScrollContainer-sc-16fmc9y-12 cqaoTV&quot;]/div[@class=&quot;LeftContainer-sc-17fwepb-0 irASBg&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-end MuiGrid-justify-xs-space-between&quot;]/div[@class=&quot;InlineOuterContainer-sc-1izdixb-0 hozzAK&quot;]/div[@class=&quot;ResultItemWrapper-sc-1izdixb-7 eVKSt&quot;]/div[@class=&quot;InlineInnerContainer-sc-1izdixb-1 kRjDnM&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-direction-xs-column&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item&quot;]/div[@class=&quot;InlineContainer-sc-1izdixb-3 bXtXiw&quot;]/p[@class=&quot;ProviderName-sc-1izdixb-8 bFmWmv&quot;]</value>
      <webElementGuid>b351cac0-2765-4ac6-91db-76482bbb4f96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@type='submit'])[6]</value>
      <webElementGuid>b8fcf298-9b64-492c-bb62-736a7f87b608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='provider-dir-outer-container']/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[11]/div[2]/div/div/div/p</value>
      <webElementGuid>e7e54618-efc9-46db-8bb3-64c40ca19770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GARY B PALATUCCI, MD']/parent::*</value>
      <webElementGuid>0691134d-6612-482d-abf4-d0534bd8d504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/div/p</value>
      <webElementGuid>84159e13-4a90-4917-91e3-9147ec81868c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = 'submit' and (text() = 'GARY B PALATUCCI, MD' or . = 'GARY B PALATUCCI, MD')]</value>
      <webElementGuid>4c4aa70a-5c10-4a55-9123-78442d71dc66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
