<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Primary Care Provider</name>
   <tag></tag>
   <elementGuidId>b7343748-26f5-4d8b-a53e-6f9b38acecc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commonsearchitem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='commonsearchitem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86214641-6020-4116-956c-41ddd924633b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commonsearchitem</value>
      <webElementGuid>7c1fb12e-f11c-4ecb-8ac7-7c0d8b715537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CommonSearchesButton-sc-14pjxxt-7 ddzmSO</value>
      <webElementGuid>e609bbaa-c54e-4d4d-88c8-ac8b36220f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary Care Provider</value>
      <webElementGuid>380097df-c592-416a-9b1c-de093ae1eb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-dir-outer-container&quot;)/div[@class=&quot;Container-sc-14pjxxt-0 bBQJOf&quot;]/div[@class=&quot;BackgroundContainer-sc-14pjxxt-1 kqfwHj&quot;]/div[@class=&quot;InnerContainer-sc-14pjxxt-2 jDNmMR&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/button[@id=&quot;commonsearchitem&quot;]</value>
      <webElementGuid>c22873ec-9577-45df-9928-9854f6ea39c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='commonsearchitem']</value>
      <webElementGuid>b9b2239c-8bf0-45fd-850f-e4f283527f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='provider-dir-outer-container']/div/div/div/div[4]/button</value>
      <webElementGuid>55a90e97-10de-4ed8-922a-69fd0ce08f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Common Searches'])[1]/following::button[1]</value>
      <webElementGuid>6918954a-f9d4-4c39-ba15-6c8783004f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directory last updated on: September 01, 2023'])[1]/following::button[1]</value>
      <webElementGuid>999b6afd-4389-40d8-a407-581b068681a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Our Plans'])[1]/preceding::button[8]</value>
      <webElementGuid>dc408615-a410-485d-b4a7-2be9199abc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info for Shoppers'])[4]/preceding::button[8]</value>
      <webElementGuid>f8ecd31d-6890-4d45-a328-a29de29a6d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>599a58ca-6c0b-4887-8eaf-4ba3d04a8808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'commonsearchitem' and (text() = 'Primary Care Provider' or . = 'Primary Care Provider')]</value>
      <webElementGuid>0bfc968e-3d55-4610-a90c-f499317bca56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
