<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_226 W 14TH ST, NEW YORK, NY, 10011</name>
   <tag></tag>
   <elementGuidId>0729b8fc-c031-4d54-92f4-22c78907c013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Address-tgo80y-27.cvqjun</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='provider-dir-outer-container']/div[2]/div/div[2]/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18311174-9321-4835-bb31-3bef0122f7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>13f78167-5257-4ed4-ac3f-86ae58d65a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ProviderAddress</value>
      <webElementGuid>d5e229ef-d08e-4083-97f9-f1db5b330291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Address-tgo80y-27 cvqjun</value>
      <webElementGuid>9a5f2fc7-68e7-4b6c-a710-ecdb92de5dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>226 W 14TH ST, NEW YORK, NY, 10011</value>
      <webElementGuid>b5b747e9-3728-4284-8a80-f9b3a6182880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-dir-outer-container&quot;)/div[@class=&quot;Container-cgp9dk-0 gIxxub&quot;]/div[@class=&quot;InnerWrapper-tgo80y-2 fNcKoj&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-7&quot;]/div[@class=&quot;DetailsCard-tgo80y-0 iNjXXg&quot;]/div[@class=&quot;Section-tgo80y-4 huAyPV&quot;]/div[@class=&quot;Address-tgo80y-27 cvqjun&quot;]</value>
      <webElementGuid>bdc61b02-38da-4296-bfc8-0810faceb26a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='provider-dir-outer-container']/div[2]/div/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>6bc61bde-c2fd-4bee-8148-adc7f59f0db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sunday'])[1]/following::div[8]</value>
      <webElementGuid>27ca757c-b64a-439b-bed3-b181d08d73af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saturday'])[1]/following::div[9]</value>
      <webElementGuid>edeaf94f-8a40-4ce8-b8f5-223ddcaed302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Directions'])[1]/preceding::div[1]</value>
      <webElementGuid>07ab2d2e-ade7-4377-aecd-0378cbd27469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Useful to Know'])[1]/preceding::div[2]</value>
      <webElementGuid>69d25061-ba75-45d6-9cb1-747445956d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='226 W 14TH ST, NEW YORK, NY, 10011']/parent::*</value>
      <webElementGuid>031ad89b-e5fd-4216-9450-1a4e7f445bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>97ff5914-fa62-4dae-a276-63359eb165c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '226 W 14TH ST, NEW YORK, NY, 10011' or . = '226 W 14TH ST, NEW YORK, NY, 10011')]</value>
      <webElementGuid>8fd7d37f-40a5-4838-82b6-3d902deb2773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
