<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KELLY A CASSANO, DO</name>
   <tag></tag>
   <elementGuidId>250325ca-75ec-4c3d-a7c4-9b88a33889c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//p[@type='submit'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ffd2b2ee-9b25-4a20-ad23-d6c4dafe3af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2756cbf3-6efe-4b06-89b0-54a1c85d973b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>e72668bd-e10b-41cd-bbf0-b838a1de62b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ProviderName</value>
      <webElementGuid>ef341eda-38d5-4172-bbce-4247415c4ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProviderName-sc-1izdixb-8 bFmWmv</value>
      <webElementGuid>f303b30e-1ab8-4264-905a-521698ffa207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KELLY A CASSANO, DO</value>
      <webElementGuid>e9f84a90-a941-4168-980f-d141a030705c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-dir-outer-container&quot;)/div[@class=&quot;OuterContainer-sc-16fmc9y-1 AGOzA&quot;]/div[@class=&quot;Container-sc-16fmc9y-2 fxuCEC&quot;]/div[@class=&quot;LeftPanel-sc-16fmc9y-3 cLnDLW&quot;]/div[@class=&quot;ScrollContainer-sc-16fmc9y-12 cqaoTV&quot;]/div[@class=&quot;LeftContainer-sc-17fwepb-0 irASBg&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-end MuiGrid-justify-xs-space-between&quot;]/div[@class=&quot;InlineOuterContainer-sc-1izdixb-0 hozzAK&quot;]/div[@class=&quot;ResultItemWrapper-sc-1izdixb-7 eVKSt&quot;]/div[@class=&quot;InlineInnerContainer-sc-1izdixb-1 kRjDnM&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-direction-xs-column&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item&quot;]/div[@class=&quot;InlineContainer-sc-1izdixb-3 bXtXiw&quot;]/p[@class=&quot;ProviderName-sc-1izdixb-8 bFmWmv&quot;]</value>
      <webElementGuid>77720f6f-2558-42c3-ab69-2fb59d4a12ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@type='submit'])[9]</value>
      <webElementGuid>d5553eef-7212-4e43-bfb9-896e1f6dad60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='provider-dir-outer-container']/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[17]/div[2]/div/div/div/p</value>
      <webElementGuid>5bb4f5d2-22f9-4b52-b677-3258787c96bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KELLY A CASSANO, DO']/parent::*</value>
      <webElementGuid>ec6f7d03-8771-4f19-94ae-82cec5d8cd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/div/div/p</value>
      <webElementGuid>a369e3cd-69ed-41ff-9ccf-3c988922e63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = 'submit' and (text() = 'KELLY A CASSANO, DO' or . = 'KELLY A CASSANO, DO')]</value>
      <webElementGuid>61a8ebe3-3831-471a-a6b3-d2214acd8316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
