<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_john</name>
   <tag></tag>
   <elementGuidId>59071eb5-5141-4d37-8b47-7a139eaead76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.UserName-sc-1oy22ma-16.hJunBi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c36b0b4-a560-4e70-9f8a-7a22d48e2060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UserName-sc-1oy22ma-16 hJunBi</value>
      <webElementGuid>19f664a4-7b7f-42ba-83d1-3942b69c6900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>john</value>
      <webElementGuid>32d7e89a-3f47-4865-8740-dbde1c01e609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;MuiToolbar-root MuiToolbar-regular MuiToolbar-gutters&quot;]/div[@class=&quot;NavRightUser-sc-1oy22ma-14 bWojoX&quot;]/span[@class=&quot;UserName-sc-1oy22ma-16 hJunBi&quot;]</value>
      <webElementGuid>f059b357-10bf-4b5a-9256-acbac3dfbaf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div[2]/div/span</value>
      <webElementGuid>43304966-ad30-4ac0-a477-85867107e3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::span[3]</value>
      <webElementGuid>1d2363f2-f9f2-4aba-9ee2-737df80c764c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Plan'])[1]/following::span[5]</value>
      <webElementGuid>d327730a-4eab-42c6-95ae-c45e87b89e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John'])[1]/preceding::span[1]</value>
      <webElementGuid>6f6b1cd4-4504-41a7-9ca5-d7d061a52ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='john']/parent::*</value>
      <webElementGuid>b769da66-df34-4bf6-920c-243674325f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>293b15a5-3691-49dc-8572-ac756bdaabf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'john' or . = 'john')]</value>
      <webElementGuid>65d79f4e-edb0-484d-a969-e33b64b7be7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
